#The Directories and extensions SECTION
SRC_MODULES_DIR	   := Src_Modules
BUILDDIRECTORY 	   := Objects
TARGETDIRECTORY	   := Release
RESDIRECTORY  	   := Resources
LIBDIRECTORY	   := Libraries
HEADERSDIRECTORY   := Headers

DLEXT	:= so
SLEXT	:= a
SRCEXT	:= c
OBJEXT	:= o
HEADEXT	:= h
SRCDIR	:= src

#Modules SECTION
MODULEA := Application
MODULEB := StaticLibTest
MODULEC	:= SharedLibTest
MODULED := DataStructures

DEPMODULES	:= $(MODULEC) $(MODULEB) 
MAINMODULE	:= $(MODULEA)

#Compiler SECTION
TARGET 		:= Application
TESTTYPE	:= Release
INSTRUCTIONS	:= x86_64
LIBRARIESTYPE	:= DYNANDSTATIC
VERSION		:= $(TESTTYPE)$(INSTRUCTIONS)$(LIBRARIESTYPE)
CC 		:= gcc
ARCH		:= ar rcs
CFLAGS		:= -Wall
MACROS		:= -D RELEASE\
		-D RESOURCES=\"/home/paul/.TemplateMakefiles/Resources/\"
#-g for Debug

#Linker SECTION
#LIBRSEARCHPATH should have an absolute path and coincide with
#LIBINSTALLDIR if installation is required
LIBSTOLINK    	:=  -l $(MODULEB)\
		-l $(MODULEC)
LIBSEARCHDIR	:= $(LIBDIRECTORY)/$(VERSION)/
LIBSRSEARCHPATH	:= /home/paul/.TemplateMakefiles/$(LIBDIRECTORY)/
LDFLAGS		:= -L ../../$(LIBSEARCHDIR) $(LIBSTOLINK) \
	-Wl,-rpath,$(LIBSRSEARCHPATH)		
#-static

#CROSSCOMPILE SECTION
CROSSCOMPILE_HOSTNAME 	:= pi
CROSSCOMPILE_SSH_HOST 	:= 192.168.1.70
CROSSCOMPILE_DIR 	:= /home/pi

#RUNNING

#This 3 variables should be left in blank if no installation is required
#otherwise problems may occur

#When used, all 3 variables should be filled even if  only one variable is
#required

#Use / at the end

EXECINSTALLDIR	:= ~/.TemplateMakefiles/$(TARGETDIRECTORY)/
LIBINSTALLDIR	:= ~/.TemplateMakefiles/$(LIBDIRECTORY)/
RESINSTALLDIR	:= ~/.TemplateMakefiles/