#!/bin/bash

rsync ../Makefile ./MainMakefile
rsync ../Src_Modules/Application/Makefile ./MainApplication
rsync ../Src_Modules/SharedLibTest/Makefile ./SharedLibrary
rsync ../Src_Modules/StaticLibTest/Makefile ./StaticLibrary
