#!/bin/bash

rsync -vzh --update ../Makefile ./MainMakefile
rsync -vzh --update ../Src_Modules/Application/Makefile ./MainApplication
rsync -vzh --update ../Src_Modules/SharedLibTest/Makefile ./SharedLibrary
rsync -vzh --update ../Src_Modules/StaticLibTest/Makefile ./StaticLibrary
